### ISSUE TITLE
p0 需求整理

### ISSUE THREAD

**Issue by jaredleechn** [ant-tool/atool-doc#1]
- [x] 目录：默认存放在 examples，支持文件类型 *.md *.js
  - [x] 生成根目录 index.html
  - [x] 为每一个 demo 生成一个 element.html 
  - [x] 支持多层级目录 demo 的生成，如 antd/table/index.md + normal-table.md + special-table.md（p2
- [x] build && watch
- [x] server
- [x] md-loader
  - [ ] 支持外链 js（p2
- [x] js-loader
  - [x] pkgName@version
  - [x] demo
  - [x] readme
  - [ ] ~~history changelog~~
  - [ ] ~~test coverage~~
- [x] 自定义模版
- ~~通过接受中间件处理，允许用户根据 *.md 中的 meta 信息进行模版自定义（p2~~

相关 react-component/react-component.github.io#11

MD写法：

``` markdown
// Meta data 用 YAML 描述配置信息，可在中间件中获取配置
// see: https://github.com/blog/1647-viewing-yaml-metadata-in-your-documents

---
config1: true
config2: 任意字符
config3: 
  - 1
  - 2
  - 3

---

## code

'''jsx(js, javascript, node)
var a = 1;
'''

## api

| 参数           | 说明                             | 类型       |  可选值 | 默认值 |
|----------------|----------------------------------|------------|---------|--------|
| dot            | 不展示数字，只有一个小红点       | boolean    |         | false  |
```

**Comment by jaredleechn** [comment]
### 面向组件

**before**

```
./
├── README.md
└── examples
    ├── a.js
    ├── a.html
    └── b.md
```

**after**

```
./
├── README.md
├── __site
│   ├── common.js
│   ├── examples
│   │   ├── a.html
│   │   ├── a.js
│   │   ├── b.html
│   │   ├── b.js
│   └── index.html
└── examples
    ├── a.js
    ├── a.html
    └── b.md

```

**Comment by benjycui** [comment]
Markdown 语法建议如下，比较好处理。

``` markdown
// Meta data 用 YAML，see: https://github.com/blog/1647-viewing-yaml-metadata-in-your-documents
---
config1: true
config2: 任意字符
config3: 
  - 1
  - 2
  - 3
---

'''jsx(js, javascript, node)
// code 还是用回 Markdown 的语法吧
var a = 1;
'''

## api

| 参数           | 说明                             | 类型       |  可选值 | 默认值 |
|----------------|----------------------------------|------------|---------|--------|
| dot            | 不展示数字，只有一个小红点       | boolean    |         | false  |
```

**Comment by jaredleechn** [comment]
啊是的，我本意也是 用 ```，但是打不出来～

**Comment by jaredleechn** [comment]
demo 文件的组织：

- 每个 md 文件对应一个 demo
- 支持多层级的 demo 组织，例如：antd/table/index.md + normal-table.md + special-table.md


demo 文件的处理：

- 通过 loader 将每个 md 处理为 html（提取 js 代码，打包成内联 js，并按规则渲染 md
- 通过脚手架增加一个 entry：doc，引入所有的 md，并控制页面交互（require('example/xx/xx.md')


这样的好处是，非常精简，而且构建和项目本身构件结合到一起，只是通过增加一个 entry

**Comment by yiminghe** [comment]
md 要支持外链 js，不希望在 md 中写大段 js

**Comment by benjycui** [comment]
> md 要支持外链 js，不希望在 md 中写大段 js

个人的想法是用命名约定，如下：
1. 每种语言一个 Markdown file：demo.zh-CN.md，demo.en-US.md
2. 在渲染 Markdown 时，会自动寻找同名的 JavaScript 文件：demo.js

用约定的方式比修改扩展 Markdown 的语法要简单。。

**Comment by jaredleechn** [comment]
讨论下来还是采取预处理 + entry 的方式，使用方式类似 atool-doc-pre && atool-build/dora
- 将 *.md 中的代码处理成 js 文件（export function(code)
- ~~增加 entry 引入所有的 js 文件、md 文件，通过 react 组织成单页~~ 因为存在可能和 demo 中使用 router 的代码冲突的问题，取消单页，采取跳转的方式，每个 js 是一个 entry

**Comment by jaredleechn** [comment]
- [ ] 自定义模版（约定通用变量
 - [ ] 自定义样式文件

**Comment by jaredleechn** [comment]
```
./
├── README.md
└── examples
    ├── a.js
    └── a.html
    └── b.md
```

**after**

```
./
├── README.md
├── site
│   ├── examples
│   │   ├── common.js
│   │   ├── common.js.map
│   │   ├── a.html
│   │   ├── a.js
│   │   ├── a.js.map
│   │   ├── b.html
│   │   ├── b.js
│   │   └── b.js.map
│   └── index.html
└── examples
    ├── a.js
    └── a.html
    └── b.md

```

**Comment by benjycui** [comment]
`site` => `__site`

**Comment by jaredleechn** [comment]
@benjycui  copy that

晚点我整理下讨论到目前的方案，放在最上面，然后删一些回复

**Comment by sorrycc** [comment]
`.map` 文件可以不生成的，用 inline 的 source-map 方案。
