### ISSUE TITLE
atool-doc 如何使用 dora 插件

### ISSUE THREAD

**Issue by soda-x** [ant-tool/atool-doc#11]
RT

虽然现在 atool-doc 在调试 demo 阶段使用 dora 来提供静态服务，但是并没有在插件层面达到互通。

如果能做到互通就更好了 。

**Comment by jaredleechn** [comment]
+1

livereload，hmr 现在都无法使用，因为都依赖了 atool-build

**Comment by jaredleechn** [comment]
@silentcloud 这部分问题应该 atool-test 也要解决

**Comment by silentcloud** [comment]
@jaredleechn 没太明白具体问题

**Comment by jaredleechn** [comment]
目前 atool-doc 是自己起了一个 dora server，然后配置 `koa-webpack-dev-middleware` 来完成的

但是如果想直接使用 dora 的 livereload 插件或者 hmr 插件是不行的，两者对 dora-plugin-webpack 有依赖

atool-test 也应该是相同的吧？
