### ISSUE TITLE
Demo 列表过长无法下拉

### ISSUE THREAD

**Issue by TomHuangCN** [ant-tool/atool-doc#23]
如题

**Comment by jaredleechn** [comment]
了解，是我设置成 fixed 的原因，内置增加一个滚动条

**Comment by TomHuangCN** [comment]
when will fix? to many demo now...

**Comment by benjycui** [comment]
其实也不建议一个页面太多 demo 吧，除非像 ant.design 这样每个 demo 都有对应的 anchor 可以直接定位，不然要找到对应的 demo 很麻烦。

**Comment by jaredleechn** [comment]
他的意思是 menu 那部分，一个组件可能有很多 demo，所以那个可以选择切换的 menu 就非常长，同时又是 fixed

**Comment by jaredleechn** [comment]
后面会在提升模版编写体验的 milestone 做成文件夹默认不展开，点击才展开的，这样多一些文件夹上的分类，就可以避免首页和 demo 页的 menu 过长问题了
