### ISSUE TITLE
支持 proxy 端口设置

### ISSUE THREAD

**Issue by superRaytin** [ant-tool/atool-doc#28]
有时候本地会起好几个服务，proxy 默认端口都是 8989，如果想起一个新的，只能先停掉别的。

所以建议把 proxy 端口设置放开，参考 dora 的做法~

**Comment by WhatAKitty** [comment]
@sorrycc 不知道有没有这个用法？特别是我在开启酷狗音乐，然后
![image](https://cloud.githubusercontent.com/assets/4178729/17959888/acfd40e2-6ad5-11e6-9db8-a4ae9b16780d.png)
出现这个问题，搞得我一脸懵逼。

**Comment by soda-x** [comment]
proxy 是支持传入端口号的

doc 现在屏蔽了传入的方式

**Comment by WhatAKitty** [comment]
@pigcan 如何使用？

**Comment by WhatAKitty** [comment]
"start": "dora --plugins \"proxy?port=8888,webpack,webpack-hmr\"",
可以了

**Comment by jaredleechn** [comment]
@WhatAKitty @superRaytin 
Feat will release in 0.6 next Tue

**Comment by jaredleechn** [comment]
bump 0.0.6

use by `atool-doc --doraPlugins proxy?port=xx`
