### ISSUE TITLE
package.json中webpack依赖的版本问题

### ISSUE THREAD

**Issue by Tankpt** [ant-tool/atool-doc#35]
是否可以改成

```
"webpack": "^1.12.2"
```

**Comment by jaredleechn** [comment]
这个是和 [atool-build](https://github.com/ant-tool/atool-build/blob/master/package.json#L56) 保持统一的，因为底层构建和配置还是使用的 atool-build

@Tankpt 是需要使用更高版本的 webpack 的功能嘛？  cc @pigcan

**Comment by Tankpt** [comment]
是的。而且而且理论上来说，1.13.X这样的版本也会兼容1.12.X，虽然在npm3这类上面没有问题，但是在老的npm2上回有错误的提示，所以建议是这样

**Comment by Tankpt** [comment]
Hello 这个问题。。不能升级么依赖么？

**Comment by jaredleechn** [comment]
ping @pigcan

**Comment by soda-x** [comment]
?

**Comment by Tankpt** [comment]
就是atool-doc里面的对webpack的依赖能否改成
```
"webpack": "^1.12.2" 
````
因为在peerDependencies声明的是
```
 "webpack": "~1.12.2"
```
如果在外面使用高版本的话会有冲突

**Comment by jaredleechn** [comment]
看了下，因为重写了 html-plugin，所以现在的确是不需要对 webpack 的 peerDeps 了，我马上去掉

thx @Tankpt 

不过 doc 所依赖的 atool-build 使用的仍然是 `1.12`，所以你的项目可能会安装多个 webpack

**Comment by jaredleechn** [comment]
fix in 0a25cb615422741ddcc3f1a26708d2a4c8cefaa9
