### ISSUE TITLE
p2 需求整理

### ISSUE THREAD

**Issue by jaredleechn** [ant-tool/atool-doc#8]
- [x] normalize cdn
- [x] Si 文档增加 tpl 说明
- [x] 自身文档增加 `##code` 说明，该节点神圣不可侵犯
- [x] `--tpl` 增加模版名入口
- [ ] ~~增加移动端模版~~
- [x] `element.ejs` 增加导航
- [ ] ~~开放预留 dom 节点自定义 id 的接口~~
- [x] 加入 meta 信息，name 字段替换为 *.html 的 title
- [x] 多目录支持
- [x] 指定 port

**Comment by benjycui** [comment]
建议 issue 要关联对应的 commit

**Comment by jaredleechn** [comment]
> 建议 issue 要关联对应的 commit

ok，之前 p2 的需求都是写在一起，所以关联起来比较麻烦，之后拆成单个 issue

**Comment by benjycui** [comment]
能拆最好，拆不了可以参考这种 https://github.com/ant-design/ant-design/issues/1259

**Comment by jaredleechn** [comment]
get it
