### ISSUE TITLE
Ant Design 官网抽取为通用建站工具

### ISSUE THREAD

**Issue by benjycui** [ant-tool/atool-doc#9]
在 atool-doc 这边开 issue 算了，说不定真的就合并了。

收集需求，先评估下。

@yiminghe @jljsj33

**Comment by kasinooya** [comment]
想建一个 antd+ 项目官网，packjson中的name是antd-plus
想把md中的import xxx from 'antd'改成自己的包名称，然后又能支持 import antd的组件

**Comment by benjycui** [comment]
> 想把md中的import xxx from 'antd'改成自己的包名称，然后又能支持 import antd的组件

这个可以用 webpack 的 resolve.alias 解决。

**Comment by jaredleechn** [comment]
@kasinooya 

https://github.com/ant-tool/atool-doc/blob/master/src/getWebpackConfig.js#L50

@benjycui 

想法是，给 atool-doc 增加单页主题，需要重构 atool-doc 的部分接口，来达到面向单页和多页同时可用

**Comment by jaredleechn** [comment]
目前 doc 支持指定模版名，后面的想法是拆分 webpackConfig 为 common 和 custom 两部分，每个模版名对应具体的模版文件和 customWebpackConfig

整个生命周期就是 webpack/dora 的生命周期

然后内置支持的所有模版通过 Constant 管理起来

```
export const tplSet = {
  github: {
    file: './src/element.ejs',
    config: './config/githubWebpackConfig.js',
  }
}
```

See [constant.js](https://github.com/ant-tool/atool-doc/blob/master/src/constant.js)

**Comment by benjycui** [comment]
Transfer to: https://github.com/benjycui/bisheng/issues/1
